2022-07-13 19:44:44,013 | INFO | telegram | CHANNEL_NAME_CLIENT environment variable isn't a valid entity. Check your environment file. 
2022-07-13 19:44:44,013 | INFO | telegram | Task <Task pending name='Task-45' coro=<set_chat_id() running at C:\Users\boxxo\PycharmProjects\forwarder_pyrogram\ForwardBot\__init__.py:58> cb=[_run_until_complete_cb() at C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\asyncio\base_events.py:184]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\ProgramData\Anaconda3\envs\forwarder_pyrogram\lib\asyncio\futures.py:384]> attached to a different loop 
